controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    jsc_mecanum_drive_controller:
      type: jsc_mecanum_controller/MecanumbotDriveController

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true

jsc_mecanum_drive_controller:
  ros__parameters:
    use_stamped_vel: false 
    fl_wheel_joint_name: fl_wheel_joint
    fr_wheel_joint_name: fr_wheel_joint
    rl_wheel_joint_name: rl_wheel_joint
    rr_wheel_joint_name: rr_wheel_joint
    wheel_radius: 0.03
    wheel_distance:
      width: 0.46
      length: 0.40
    publish_wheel_joint_states: true 